export const siteStylesheets = [
  "/wp-content/plugins/jeg-elementor-kit/assets/css/elements/main.css",
  "/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css",
  "/wp-content/plugins/woocommerce/assets/css/woocommerce.css",
  "/wp-content/plugins/elementor/assets/lib/flatpickr/flatpickr.min.css",
  "/wp-content/plugins/enix-booking-rental-woocommerce/public/css/enix-public.css",
  "/wp-content/plugins/qi-addons-for-elementor/assets/css/grid.min.css",
  "/wp-content/plugins/qi-addons-for-elementor/assets/css/helper-parts.min.css",
  "/wp-content/plugins/qi-addons-for-elementor/assets/css/main.min.css",
  "/wp-content/plugins/elementor/assets/css/frontend.min.css",
  "/wp-content/uploads/elementor/css/post-102.css",
  "/wp-content/plugins/elementor/assets/css/widget-icon-list.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-heading.min.css",
  "/wp-content/plugins/elementor/assets/lib/animations/styles/fadeInRight.min.css",
  "/wp-content/plugins/jeg-elementor-kit/assets/js/sweetalert2/sweetalert2.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-image.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-counter.min.css",
  "/wp-content/plugins/qi-addons-for-elementor/assets/plugins/swiper/8.4.5/swiper.min.css",
  "/wp-content/plugins/elementor/assets/css/conditionals/e-swiper.min.css",
  "/wp-content/plugins/elementor/assets/lib/animations/styles/zoomIn.min.css",
  "/wp-content/plugins/elementor/assets/lib/animations/styles/fadeInLeft.min.css",
  "/wp-content/plugins/pro-elements/assets/css/widget-loop-common.min.css",
  "/wp-content/plugins/pro-elements/assets/css/widget-loop-grid.min.css",
  "/wp-content/plugins/jeg-elementor-kit/assets/js/tiny-slider/tiny-slider.css",
  "/wp-content/uploads/elementor/css/post-98.css",
  "/wp-content/uploads/elementor/css/post-391.css",
  "/wp-content/uploads/elementor/css/post-624.css",
  "/wp-content/uploads/elementor/css/post-427.css",
  "/wp-content/uploads/elementor/css/post-469.css",
  "/wp-content/uploads/elementor/css/post-1158.css",
  "/wp-content/uploads/elementor/css/post-1326.css",
  "/wp-includes/css/dist/block-library/style.min.css",
  "/wp-content/plugins/pro-elements/assets/css/widget-form.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-google_maps.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-video.min.css",
  "/wp-content/themes/hello-elementor/assets/css/reset.css",
  "/wp-content/themes/hello-elementor/assets/css/theme.css",
  "/wp-content/themes/hello-elementor/assets/css/header-footer.css",
  "/wp-content/plugins/pro-elements/assets/css/widget-nav-menu.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-divider.min.css",
  "/wp-content/plugins/elementor/assets/css/widget-social-icons.min.css",
  "/wp-content/plugins/elementor/assets/css/conditionals/apple-webkit.min.css",
  "/wp-content/uploads/elementor/css/post-24.css",
  "/wp-content/uploads/elementor/css/post-164.css",
  "/wp-content/plugins/creame-whatsapp-me/public/css/joinchat.min.css",
  "/wp-content/plugins/jeg-elementor-kit/assets/fonts/jkiticon/jkiticon.css",
];

/** Loaded with media query — file has no internal @media wrappers */
export const conditionalStylesheets = [
  {
    href: "/wp-content/plugins/woocommerce/assets/css/woocommerce-smallscreen.css",
    media: "only screen and (max-width: 768px)",
  },
];

export const siteFonts = [
  "https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100..900;1,100..900&display=swap",
  "https://fonts.googleapis.com/css2?family=El+Messiri:wght@400..700&display=swap",
];
